config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
             controllers: {
               # registrations: 'auth/users/registrations',
               sessions: 'auth/users/sessions'
             }

  scope module: 'portal' do
    resource  :account
    resources :agents
    resources :projects
    resources :project_assignments, only: [:create, :destroy]
    resources :project_reports, only: [:create]

    # root to: 'dashboard#show'
    root to: 'projects#index'
  end

  mount FieldActivitiesAPI::Root => '/'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollectorPro</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/portal.html.erb
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="">

  <title><%= yield :page_title %> Donatio </title>

  <link rel="apple-touch-icon" href="../assets/images/apple-touch-icon.png">
  <link rel="shortcut icon" href="../assets/images/favicon.ico">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'portal', media: 'all', 'data-turbolinks-track' => true %>

  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

  <% if false # TODO: find these scripts %>
      <!--[if lt IE 9]>
      <script src="../assets/vendor/html5shiv/html5shiv.min.js"></script>
      <![endif]-->
      <!--[if lt IE 10]>
      <script src="../assets/vendor/media-match/media.match.min.js"></script>
      <script src="../assets/vendor/respond/respond.min.js"></script>
      <![endif]-->
  <% end %>

  <%= javascript_include_tag 'vendor/modernizr/modernizr.min' %>
  <%= javascript_include_tag 'vendor/breakpoints/breakpoints.min' %>
  <script>
      Breakpoints();
  </script>
  <link id="skinStyle" href="../../assets/skins/purple.css" rel="stylesheet" type="text/css">

  <style type="text/css" media="screen">
      <%= yield :styles %>
  </style>


</head>

<body class="<%= yield :page_class %>">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega navbar-inverse bg-purple-600" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle hamburger hamburger-close navbar-toggle-left hided"
            data-toggle="menubar">
      <span class="sr-only">Toggle navigation</span>
      <span class="hamburger-bar"></span>
    </button>
    <button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-collapse"
            data-toggle="collapse">
      <i class="icon wb-more-horizontal" aria-hidden="true"></i>
    </button>
    <div class="navbar-brand navbar-brand-center">
      <!--<img class="donatio-logo" src="#" title="Donatio">-->
      <span class="navbar-brand-text">
      <%= image_tag("donatio-logo.png", class: "navbar-brand-logo", title: "Donatio") %>

      </span>
    </div>
    <button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-search"
            data-toggle="collapse">
      <span class="sr-only">Toggle Search</span>
      <i class="icon wb-search" aria-hidden="true"></i>
    </button>
  </div>

  <div class="navbar-container container-fluid">
    <!-- Navbar Collapse -->
    <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
      <!-- Navbar Toolbar -->
      <ul class="nav navbar-toolbar">
        <li class="hidden-float" id="toggleMenubar">
          <a data-toggle="menubar" href="index.html#" role="button">
            <i class="icon hamburger hamburger-arrow-left">
              <span class="sr-only">Toggle menubar</span>
              <span class="hamburger-bar"></span>
            </i>
          </a>
        </li>
        <li class="hidden-xs" id="toggleFullscreen">
          <a class="icon icon-fullscreen" data-toggle="fullscreen" href="index.html#" role="button">
            <span class="sr-only">Toggle fullscreen</span>
          </a>
        </li>
        <li class="hidden-float">
          <a class="icon wb-search" data-toggle="collapse" href="index.html#" data-target="#site-navbar-search"
             role="button">
            <span class="sr-only">Toggle Search</span>
          </a>
        </li>
      </ul>
      <!-- End Navbar Toolbar -->

      <!-- Navbar Toolbar Right -->
      <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
        <li class="dropdown">
          <a class="navbar-avatar dropdown-toggle" data-toggle="dropdown" href="index.html#" aria-expanded="false"
             data-animation="scale-up" role="button">
                <i class="icon wb-more-vertical" aria-hidden="true"></i>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li role="presentation">
              <a href="javascript:void(0)" role="menuitem"><i class="icon wb-user" aria-hidden="true"></i> Profile</a>
            </li>
            <li role="presentation">
              <a href="javascript:void(0)" role="menuitem"><i class="icon wb-payment" aria-hidden="true"></i> Billing</a>
            </li>
            <li role="presentation">
              <a href="<%= account_path %>" role="menuitem"><i class="icon wb-settings" aria-hidden="true"></i>

                Settings

              </a>

            </li>
            <li class="divider" role="presentation"></li>
            <li role="presentation">
              <a href="<%= destroy_user_session_path %>" role="menuitem" data-method="delete">
                <i class="icon wb-power" aria-hidden="true"></i> Logout</a>
            </li>
          </ul>
        </li>
      </ul>
      <!-- End Navbar Toolbar Right -->
    </div>
    <!-- End Navbar Collapse -->

    <!-- Site Navbar Seach -->
    <div class="collapse navbar-search-overlap" id="site-navbar-search">
      <form role="search">
        <div class="form-group">
          <div class="input-search">
            <i class="input-search-icon wb-search" aria-hidden="true"></i>
            <input type="text" class="form-control" name="site-search" placeholder="Find Collector or Event...">
            <button type="button" class="input-search-close icon wb-close" data-target="#site-navbar-search"
                    data-toggle="collapse" aria-label="Close"></button>
          </div>
        </div>
      </form>
    </div>
    <!-- End Site Navbar Seach -->
  </div>
</nav>
<div class="site-menubar site-menubar-light">
  <div class="site-menubar-body">
    <div>
      <div>
        <ul class="site-menu">
          <li class="site-menu-category"><%= current_account.name %></li>
          <!--
          <li class="site-menu-item <%#= active?('portal/dashboard') %>">
            <a class="animsition-link" href="<%#= root_path %>">
              <i class="site-menu-icon wb-dashboard" aria-hidden="true"></i>
              <span class="site-menu-title">Dashboard</span>
            </a>
          </li>
          -->

          <li class="site-menu-item <%= active?('portal/projects') %>">
            <a class="animsition-link" href="<%= projects_path %>">
              <i class="site-menu-icon wb-flag" aria-hidden="true"></i>
              <span class="site-menu-title">Events</span>
            </a>
          </li>
          <li class="site-menu-item <%= active?('portal/agents') %>">
            <a class="animsition-link" href="<%= agents_path %>">
              <i class="site-menu-icon wb-users" aria-hidden="true"></i>
              <span class="site-menu-title">Collectors</span>
            </a>
          </li>
        </ul>

      </div>
    </div>
  </div>

  <div class="site-menubar-footer">
    <a href="javascript: void(0);" class="fold-show" data-placement="top" data-toggle="tooltip"
       data-original-title="Settings">
      <span class="icon wb-settings" aria-hidden="true"></span>
    </a>
    <a href="javascript: void(0);" data-placement="" data-toggle="" data-original-title="">
      <!--<span class="icon wb-eye-close" aria-hidden="true"></span>-->
    </a>
    <a href="<%= destroy_user_session_path %>" data-method="delete" data-placement="top" data-toggle="tooltip" data-original-title="Logout">
      <span class="icon wb-power" aria-hidden="true"></span>
    </a>
  </div>
</div>

<!-- Page -->
<div class="page animsition" style="animation-duration: 0.8s; opacity: 1;">
  <!-- Page header -->

  <!-- Page content -->
  <div class="page-content container-fluid">
    <%= yield %>
  </div>
</div>
</div>
<!-- End Page -->


<!-- Footer -->
<footer class="site-footer">
  <!--<span class="site-footer-legal">© 2015 <a href="http://themeforest.net/item/remark-responsive-bootstrap-admin-template/11989202">Remark</a></span>-->
  <div class="site-footer-right">
    Powered By
    <!--<i class="red-600 wb wb-heart"></i> by -->
    <a href="#">cKt</a>
  </div>
</footer>

<%= javascript_include_tag 'portal', 'data-turbolinks-track' => true %>

<script>
    (function(document, window, $) {
        'use strict';

        var Site = window.Site;
        $(document).ready(function() {
            Site.run();

    <%= render partial: 'portal/flash_notifications' %>
            <%= yield :document_ready %>
        });
    })(document, window, jQuery);
</script>

</body>

</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html class="no-js css-menubar" lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description" content="bootstrap admin template">
  <meta name="author" content="">

  <title>Donatio</title>

  <link rel="apple-touch-icon" href="../../assets/images/apple-touch-icon.png">
  <link rel="shortcut icon" href="../../assets/images/favicon.ico">

  <%= stylesheet_link_tag 'sessions', media: 'all', 'data-turbolinks-track' => true %>
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

  <% if false # TODO: find these scripts %>
      <!--[if lt IE 9]>
      <script src="../assets/vendor/html5shiv/html5shiv.min.js"></script>
      <![endif]-->
      <!--[if lt IE 10]>
      <script src="../assets/vendor/media-match/media.match.min.js"></script>
      <script src="../assets/vendor/respond/respond.min.js"></script>
      <![endif]-->
  <% end %>

  <%= javascript_include_tag 'vendor/modernizr/modernizr.min' %>
  <%= javascript_include_tag 'vendor/breakpoints/breakpoints.min' %>
  <script>
      Breakpoints();
  </script>
</head>
<body class="page-login-v3 layout-full">
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<!-- Page -->
<%= yield %>
<!-- End Page -->

<%= javascript_include_tag 'sessions', 'data-turbolinks-track' => true %>
<script>
    (function(document, window, $) {
        'use strict';

        var Site = window.Site;
        $(document).ready(function() {
            Site.run();
            <%= render partial: 'portal/flash_notifications' %>
        });
    })(document, window, jQuery);
</script>
</body>

</html>